name: Punishments
version: '1.0'
main: xyz.propsik.punishments.Punishments
api-version: '1.21'
commands:
  ban:
    description: Bans a player from the server permanently.
    permission: punishments.command.ban
    usage: "§6§lUSAGE: §e/ban <player> [reason]"
  punishments:
    description: Info command for the Punishments plugin.
