name: Punishments
version: '1.0'
main: xyz.propsik.punishments.Punishments
api-version: '1.21'
commands:
  ban:
    description: idk
    permission: punishments.command.ban
  gettestrecord:
    description: idk
  revoketestrecord:
    description: idk